packages:
  apt:
    - name: python3-pip
      state: present
    - name: pipenv
      state: present
    - name: htop
      state: present
    - name: lsof
      state: present
    - name: jq
      state: present
    - name: snapd
      state: present
  snap:
    - name: yq
      state: present
